"""This module contains the ids of the components in the app layout."""

UPLOAD_BUTTON = "upload_button"
UPLOAD_DATA = "upload-data"
UPLOAD_OUTPUT = "output-data-upload"
STORE_DATA = "store-data"
BUTTON_PROCESS_PUMP = "button-process-pump"
OUTPUT_CONTAINER = "output-container"
OUTPUT_PROCESS_PUMP = "output-process-pump"
OUTPUT_SUMMARY_TABLE = "output-summary-table"
DOWNLOAD_BUTTON = "download-button"
DOWNLOAD_OUTPUT = "output-data-download"
LOADING_PROCESS_PUMP = "loading-process-pump"
GRAPH_REPORT_ENERGY_SAVINGS = "graph-report-energy-savings"
