UPLOAD_BUTTON = "upload_button"
UPLOAD_DATA = "upload-data"
UPLOAD_OUTPUT = "output-data-upload"
STORE_DATA = "store-data"
BUTTON_PROCESS_PUMP = "button-process-pump"
OUTPUT_PROCESS_PUMP = "output-process-pump"
