"""This module contains the ids of the components in the app layout."""

UPLOAD_BUTTON = "upload_button"
UPLOAD_DATA = "upload-data"
UPLOAD_OUTPUT = "output-data-upload"
STORE_DATA = "store-data"
BUTTON_PROCESS_PUMP = "button-process-pump"
OUTPUT_CONTAINER = "output-container"
OUTPUT_PROCESS_PUMP = "output-process-pump"
OUTPUT_SUMMARY_TABLE = "output-summary-table"
DOWNLOAD_BUTTON = "download-button"
DOWNLOAD_OUTPUT = "output-data-download"
LOADING_PROCESS_PUMP = "loading-process-pump"
GRAPH_REPORT_ENERGY_SAVINGS = "graph-report-energy-savings"
PUMP_DESIGN_INPUT_CONTAINER = "pump-design-input-container"
PUMP_DESIGN_RATED_HEAD = "pump-design-rated-head"
PUMP_DESIGN_RATED_FLOW = "pump-design-rated-flow"
PUMP_DESIGN_RATED_EFFICIENCY = "pump-design-rated-efficiency"
PUMP_DENSITY = "pump-density"
PUMP_OPERATION_INPUT_CONTAINER = "pump-operation-input-container"
FLOW_SPREAD = "flow-spread"
OPERATION_HOURS_CONTAINER = "operation-hours-container"
NORMAL_HOURS_BUTTON = "normal-hours-button"